CONFIG_LZ4=y
CONFIG_LZ4_FRAME_SUPPORT=y
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_HEAP_MEM_POOL_SIZE=150000
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=150000
CONFIG_CODE_DATA_RELOCATION=y
CONFIG_CODE_DATA_RELOCATION_SRAM=y
